export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILURE = 'FETCH_COUNTRY_FAILURE';
export const CURRENT_PAGE = 'CURRENT_PAGE';
export const TOTAL_PAGES = 'TOTAL_PAGES';
export const ORDER = 'ORDER';
export const FILTER_CONTINENT = 'FILTER_CONTINENT';

export const FETCH_TOP_COUNTRIES_SUCCESS = 'FETCH_TOP_COUNTRIES_SUCCESS';
export const FETCH_TOP_COUNTRIES_REQUEST = 'FETCH_TOP_COUNTRIES_REQUEST';
export const FETCH_TOP_COUNTRIES_FAILURE = 'FETCH_TOP_COUNTRIES_FAILURE';

export const FETCH_COUNTRY_REQUEST_ID = 'FETCH_COUNTRY_REQUEST_ID';
export const FETCH_COUNTRY_SUCCESS_ID = 'FETCH_COUNTRY_SUCCESS_ID';
export const FETCH_COUNTRY_FAILURE_ID = 'FETCH_COUNTRY_FAILURE_ID';


export const FETCH_COUNTRY_REQUEST_NAME = 'FETCH_COUNTRY_REQUEST_NAME';
export const FETCH_COUNTRY_SUCCESS_NAME = 'FETCH_COUNTRY_SUCCESS_NAME';
export const FETCH_COUNTRY_FAILURE_NAME = 'FETCH_COUNTRY_FAILURE_NAME';


export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';

export const FETCH_ACTIVITY_REQUEST = 'FETCH_ACTIVITY_REQUEST';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_FAILURE = 'FETCH_ACTIVITY_FAILURE';

export const ARRORW_SORT_ID = 'ARRORW_SORT_ID';