export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILURE = 'FETCH_COUNTRY_FAILURE';
export const CURRENT_PAGE = 'CURRENT_PAGE';
export const TOTAL_PAGES = 'TOTAL_PAGES';

export const FETCH_COUNTRY_REQUEST_ID = 'FETCH_COUNTRY_REQUEST_ID';
export const FETCH_COUNTRY_SUCCESS_ID = 'FETCH_COUNTRY_SUCCESS_ID';
export const FETCH_COUNTRY_FAILURE_ID = 'FETCH_COUNTRY_FAILURE_ID';
